require_relative '../Books-Labels/book'
require_relative '../Books-Labels/label'
require_relative '../MusicAlbums-Genres/classes/music_album'
require_relative '../MusicAlbums-Genres/classes/genre'
require_relative '../Movies-Source/movie'
require_relative '../Movies-Source/source'
require_relative '../Games-Authors/author'
require_relative '../Games-Authors/game'
